import { getTopicsUsed } from "../../models/linkedinPostModel.js";

const techTopics = [
  "Artificial Intelligence in Healthcare",
  "Edge AI vs Cloud AI",
  "Future of Large Language Models",
  "Generative AI Use Cases",
  "Prompt Engineering Techniques",
  "Zero Trust Security",
  "Quantum Computing Basics",
  "Quantum Cryptography",
  "Ethics in AI Development",
  "Bias in Machine Learning Models",
  "Low-Code No-Code Platforms",
  "Serverless Architecture",
  "Containerization with Docker",
  "Kubernetes Best Practices",
  "Infrastructure as Code",
  "DevOps Culture",
  "Site Reliability Engineering",
  "Chaos Engineering",
  "Observability vs Monitoring",
  "FinOps in Cloud",
  "Cloud Cost Optimization",
  "Data Privacy Laws (GDPR, CCPA)",
  "Explainable AI",
  "Neural Network Architectures",
  "Federated Learning",
  "Reinforcement Learning Applications",
  "Self-Supervised Learning",
  "AI in Cybersecurity",
  "Natural Language Processing",
  "Speech Recognition Advances",
  "Computer Vision Trends",
  "Digital Twins in Industry",
  "IoT Security Challenges",
  "5G and Edge Computing",
  "Blockchain for Supply Chain",
  "NFTs beyond Art",
  "Smart Contracts Use Cases",
  "DeFi Explained",
  "Blockchain Scalability Solutions",
  "Web3 and Decentralized Apps",
  "Cybersecurity Threats 2025",
  "Phishing Prevention Techniques",
  "SOC Modernization",
  "Dark Web Intelligence",
  "Zero-Day Vulnerabilities",
  "Passwordless Authentication",
  "Digital Identity Management",
  "Privacy Enhancing Technologies",
  "Homomorphic Encryption",
  "Multi-Factor Authentication Trends",
  "Post-Quantum Cryptography",
  "Open Source Security",
  "Data Fabric Architecture",
  "Data Mesh vs Data Lakehouse",
  "Modern Data Stack",
  "Data Governance Challenges",
  "Real-Time Data Analytics",
  "Streaming Data with Kafka",
  "ETL vs ELT",
  "Data Quality Metrics",
  "Big Data Trends",
  "Graph Databases Use Cases",
  "Time-Series Databases",
  "SQL vs NoSQL Debate",
  "Headless CMS Platforms",
  "Composable Architecture",
  "API Management",
  "API Security",
  "REST vs GraphQL",
  "API Documentation Best Practices",
  "Software Design Patterns",
  "SOLID Principles in Practice",
  "Clean Code Techniques",
  "Code Review Culture",
  "Pair Programming Benefits",
  "Technical Debt Management",
  "Refactoring Legacy Systems",
  "Agile Methodologies",
  "Scrum vs Kanban",
  "Lean Software Development",
  "Product Discovery Process",
  "Design Sprints",
  "User Story Mapping",
  "MVP Development Strategy",
  "Startup Tech Challenges",
  "Scaling Engineering Teams",
  "Hiring for Tech Roles",
  "Retention in Tech Teams",
  "Mentorship in Tech",
  "Women in Technology",
  "Inclusive Product Design",
  "Accessibility in Tech",
  "Neurodiversity in Tech",
  "Career Switching into Tech",
  "Remote Work for Developers",
  "Hybrid Work Culture",
  "Product-Led Growth",
  "Customer-Centric Development",
  "UX Research Methods",
  "User Testing Best Practices",
  "Design Systems",
  "Motion Design in UX",
  "Microinteractions in UI",
  "Dark Mode UX Considerations",
  "Typography in UI Design",
  "Designing for Mobile",
  "Progressive Web Apps",
  "Cross-Platform Development",
  "Flutter vs React Native",
  "React.js Ecosystem",
  "Vue.js vs React.js",
  "Svelte in Production",
  "Micro-Frontend Architecture",
  "WebAssembly Use Cases",
  "JavaScript Framework Fatigue",
  "TypeScript Adoption",
  "Functional Programming in JS",
  "RxJS and Reactive Programming",
  "Front-End Performance Optimization",
  "Lazy Loading Techniques",
  "Static Site Generators",
  "Jamstack Architecture",
  "SEO for SPAs",
  "Browser Security Features",
  "Web Accessibility Guidelines",
  "Responsive Web Design",
  "CSS Grid vs Flexbox",
  "Tailwind CSS Best Practices",
  "State Management Libraries",
  "Monorepos vs Polyrepos",
  "CI/CD Pipelines",
  "GitOps Explained",
  "Terraform in Cloud Infrastructure",
  "Ansible vs Chef vs Puppet",
  "Cloud Native Observability",
  "Incident Response Automation",
  "Incident Retrospectives",
  "SaaS Pricing Strategies",
  "B2B vs B2C Product Differences",
  "Customer Journey Mapping",
  "User Activation Metrics",
  "A/B Testing in Product Dev",
  "Growth Hacking in Tech",
  "Venture Capital Trends",
  "Startup Fundraising Strategies",
  "Tech Due Diligence",
  "Mergers & Acquisitions in Tech",
  "IPO Readiness for Tech Cos",
  "AI Regulations Globally",
  "AI for Environmental Solutions",
  "AI in Financial Services",
  "AI for Fraud Detection",
  "Digital Health Tech",
  "Wearable Health Devices",
  "Personalized Medicine",
  "Robotic Process Automation",
  "Digital Transformation Challenges",
  "ITSM and Modern Enterprises",
  "Agile at Scale",
  "Digital Workplace Trends",
  "Virtual Collaboration Tools",
  "Digital Experience Platforms",
  "SaaS Compliance",
  "FinTech Innovations",
  "RegTech Solutions",
  "InsurTech Disruption",
  "AI in LegalTech",
  "PropTech Digitalization",
  "Cyber Insurance",
  "MarTech Trends",
  "EdTech Future",
  "Gaming Industry Tech",
  "AR in Retail",
  "VR in Healthcare",
  "Mixed Reality Use Cases",
  "Spatial Computing",
  "Metaverse Development Tools",
  "3D Modeling in Tech",
  "Digital Avatars",
  "Privacy in the Metaverse",
  "Data Sovereignty Issues",
  "Digital Sustainability",
  "Green Coding Practices",
  "Energy-Efficient Data Centers",
  "e-Waste Management",
  "Circular Economy in Tech",
  "Digital Carbon Footprint",
  "Tech for Good Initiatives",
  "Women Founders in Tech",
  "Tech and Mental Health",
  "Productivity Hacks for Engineers",
  "Burnout in Tech",
  "Engineering Leadership Lessons",
  "Product Management Myths",
  "Technical Writing Skills",
  "Public Speaking for Techies",
  "Personal Branding in Tech",
  "Building a LinkedIn Presence",
  "Networking Strategies",
  "Conference Speaking Tips",
  "Blogging as a Developer",
  "Podcasting for Tech",
  "Tech Book Recommendations",
  "Learning Roadmaps for Tech",
  "Interview Prep for Engineers",
  "System Design Interviews",
  "Behavioral Interviews",
  "Salary Negotiation in Tech",
  "Freelancing in Tech",
  "Tech Consulting",
  "Tech Entrepreneurship",
  "Remote Freelance Platforms",
  "Digital Nomad Life",
  "Open Source Contributions",
  "Hackathons Participation",
  "Patents in Tech",
  "Legal Aspects of Software Dev",
  "GDPR Compliance in Software",
  "US Data Privacy Laws",
  "China’s Tech Regulations",
  "Data Localization Laws",
  "Tech in Emerging Markets",
  "Digital Payments Evolution",
  "Buy Now Pay Later Tech",
  "Tech in Supply Chain",
  "Robotics Automation",
  "Cobots in Manufacturing",
  "Smart Warehousing",
  "Drones in Logistics",
  "Satellite Tech Innovations",
  "Autonomous Vehicles",
  "EV Charging Infrastructure",
  "Battery Tech Advancements",
  "Smart Cities Development",
  "Urban Tech Trends",
  "PropTech SaaS",
  "Digital Twins in Buildings",
  "3D Printing in Industry",
  "Additive Manufacturing",
  "Cyber Physical Systems",
  "Industrial IoT",
  "Predictive Maintenance",
  "Digital Manufacturing",
  "Cyber Warfare Trends",
  "Digital Espionage",
  "AI in Military Applications",
  "Space Tech Startups",
  "Asteroid Mining",
  "Satcom Innovations",
  "Undersea Cables Security",
  "Green Cloud Computing",
  "Multi-Cloud Strategies",
  "Cloud Interoperability",
  "Cloud Regulatory Compliance",
  "IoT Connectivity Protocols",
  "LPWAN Technologies",
  "Industrial Automation Software",
  "Tech Ethics Committees",
  "Corporate Digital Responsibility",
  "Digital Skills Gap",
  "Upskilling in Tech",
  "Tech Apprenticeships",
  "Diversity Metrics in Tech",
  "Disability Inclusion in Tech",
  "AI in Agriculture",
  "Food Tech Innovations",
  "Vertical Farming Technology",
  "Supply Chain Traceability",
  "Digital Farming Platforms",
  "Smart Grid Technology",
  "Energy Trading Platforms",
  "CleanTech Startups",
  "Environmental Data Platforms",
  "Ocean Tech Innovations",
  "Digital Twins in Energy",
  "Nuclear Tech Innovations",
  "Battery Recycling Technology",
  "Data Storytelling",
  "AI Art and Creativity",
  "Ethical AI Art",
  "Deepfake Detection",
  "Synthetic Media Future",
  "AI and Music Generation",
  "Voice Cloning Ethics",
  "AI Writing Tools",
  "AI and Copyright Laws",
  "AI and Journalism",
  "LLM Hallucinations",
  "Memory in AI Models",
  "TinyML Applications",
  "On-Device AI",
  "AI in Wearables",
  "Emotion AI",
  "Digital Assistants Evolution",
  "Conversational AI",
  "Chatbot Design Best Practices",
  "Speech Synthesis Advances",
  "Voice UX Design",
  "Emotion Detection via Voice",
  "AI in Video Analysis",
  "Sports Tech Innovations",
  "Fan Engagement Tech",
  "Smart Stadiums",
  "Esports Analytics",
  "Digital Refereeing Systems",
  "Fantasy Sports Platforms",
  "Microservices vs Monoliths",
  "Domain-Driven Design",
  "Event-Driven Architecture",
  "CQRS Pattern",
  "Hexagonal Architecture",
  "Test-Driven Development",
  "Behavior-Driven Development",
  "API Contract Testing",
  "Unit Testing Tools",
  "Integration Testing Strategies",
  "Performance Testing",
  "Load Testing with k6",
  "Security Testing Tools",
  "Penetration Testing Techniques",
  "Static Code Analysis",
  "Dependency Management",
  "Package Vulnerability Scanning",
  "Code Quality Metrics",
  "DevSecOps Practices",
  "Data Ethics",
  "Digital Twins in Healthcare",
  "AI in Biotech",
  "Personal Genomics",
  "Bioinformatics Trends",
  "Genome Sequencing Tech",
  "Health Data Privacy",
  "Medical Devices Software",
  "Regulations in Health Tech",
  "Digital Biomarkers",
  "Telemedicine Future",
  "Wearable Tech Regulations",
  "Mental Health Apps",
  "Digital Therapeutics",
  "Patient Engagement Platforms",
  "Health Chatbots",
  "AI for Medical Imaging",
  "Smart Hospitals",
  "Remote Patient Monitoring",
  "Predictive Health Analytics",
  "AI in Clinical Trials",
  "Healthcare Interoperability",
  "FHIR Standards",
  "Electronic Health Records",
  "Blockchain for Health Data",
  "Precision Medicine",
  "Cancer Detection Algorithms",
  "Radiology AI",
  "Surgical Robotics",
  "AR in Surgery",
  "VR in Medical Training",
  "Assistive Tech for Disabilities",
  "Prosthetics Innovation",
  "Exoskeletons for Mobility",
  "Smart Contact Lenses",
  "Digital Pathology",
  "AI for Drug Discovery",
  "Synthetic Biology",
  "DNA Data Storage",
  "Biohacking",
  "Lab Automation",
  "Green Biotechnology",
  "Cell and Gene Therapy",
  "Digital Farming Data Platforms",
  "Weather Tech Innovations",
  "Climate Modeling with AI",
  "Carbon Capture Tech",
  "Environmental IoT Sensors",
  "Smart Irrigation Systems",
  "Tech for Disaster Response",
  "Emergency Alert Systems",
  "Digital Risk Management",
  "Digital Twins in Transportation",
  "Fleet Management Systems",
  "Vehicle Telematics",
  "Smart Parking Solutions",
  "EV Fleet Operations",
  "Drone Delivery Systems",
  "Autonomous Drones",
  "Air Traffic Management Tech",
  "Space Debris Tracking",
  "Satellite Imagery Analysis",
  "Digital Asset Management",
  "Knowledge Graphs",
  "Data Lineage Tools",
  "Data Catalog Platforms",
  "Data Product Thinking",
  "Product Analytics",
  "Feature Flagging",
  "Release Management",
  "Tech Debt Documentation",
  "Developer Experience (DevEx)",
  "Engineering Productivity Metrics",
  "Platform Engineering",
  "Internal Developer Platforms",
  "Software Supply Chain Security",
  "Dependency Confusion Attacks",
  "Software Bill of Materials",
  "API Economy",
  "Digital Marketplaces",
  "Tech Marketplaces",
  "Micro SaaS Startups",
  "AI Co-Pilots for Developers",
  "AI in Game Development",
  "Procedural Content Generation",
  "Cloud Gaming Infrastructure",
  "Latency in Gaming",
  "Player Behavior Analytics",
  "Digital Collectibles",
  "Virtual Goods Economy",
  "Blockchain Gaming",
  "Play-to-Earn Models",
  "Digital Twin Avatars",
  "Virtual Influencers",
  "Digital Identity in Web3",
  "Tech Trends for 2030",
  "Virtual Reality in Education",
  "AI in Wildlife Conservation",
  "The Future of Smart Glasses",
  "Privacy Concerns in Smart Homes",
  "Blockchain for Art Authentication",
  "Voice Biometrics",
  "Zero Trust Architecture",
  "Emotion AI",
  "AI-Powered Creativity Tools",
  "Quantum Cryptography",
  "5G and Smart Cities",
  "AI in Music Composition",
  "Green Data Centers",
  "Neural Implants",
  "Brainwave Interfaces",
  "Robotics in Agriculture",
  "Robotics in Construction",
  "Battery Swapping Networks",
  "Digital Therapeutics",
  "AI for Legal Analytics",
  "Computer Vision in Sports",
  "NFTs Beyond Art",
  "Deepfake Detection",
  "AI-Driven Drug Discovery",
  "Digital-Only Banks",
  "AI-Generated Avatars",
  "Synthetic Voices",
  "Robotic Process Automation Ethics",
  "Li-Fi Technology",
  "Swarm Robotics",
  "Bioinformatics Advances",
  "Edge AI Hardware",
  "AI for Disaster Prediction",
  "Haptic Feedback Devices",
  "AI in Cybersecurity Threat Hunting",
  "Predictive Maintenance",
  "Cloud-Native Security",
  "API Security Best Practices",
  "Real-Time Data Streaming",
  "Smart Stadiums",
  "AI in Journalism",
  "AI for Climate Modeling",
  "Urban Tech Innovations",
  "Space Traffic Management",
  "AI for Wildlife Poaching Prevention",
  "Food Waste Tracking Tech",
  "Wearable Medical Devices",
  "Digital ID Verification",
  "AI in Pathology",
  "Autonomous Retail Stores",
  "Data Sovereignty Laws",
  "Tech for Disability Inclusion",
  "Digital Twins of People",
  "AI Bias Audits",
  "Automated UI Testing",
  "Explainable AI Tools",
  "Federated Learning Models",
  "Synthetic Medical Data",
  "E-Sports Tech Innovations",
  "Game Streaming Technology",
  "Cloud Gaming Infrastructure",
  "Serverless AI Models",
  "AI-Assisted Architecture Design",
  "Nanotech Sensors",
  "Next-Gen Computer Chips",
  "Gesture Recognition",
  "Computer Vision in Healthcare",
  "Autonomous Freight Trucks",
  "Satellite Constellations",
  "Cloud Robotics",
  "Robotics in Warehouses",
  "Tech for Elderly Care",
  "Emotion Recognition in Video Calls",
  "Digital Contact Tracing",
  "Privacy in Genomic Data",
  "Undersea Data Cables",
  "Smart Waste Management",
  "Blockchain for Real Estate",
  "Energy Harvesting Tech",
  "Contactless Biometric Systems",
  "AI in Emergency Response",
  "AI for Space Exploration",
  "Satellite Internet Challenges",
  "AI in Archaeology",
  "Robotics for Hazardous Environments",
  "Tech for Sustainable Fishing",
  "GeoAI",
  "Emotion Recognition in Ads",
  "Digital Product Passports",
  "Virtual Try-On Technologies",
  "Drone Delivery Regulations",
  "Autonomous Drones for Surveys",
  "Blockchain for Voting",
  "WebAssembly Adoption",
  "Quantum Machine Learning",
  "Mixed Reality Workspaces",
  "Smart Airports",
  "AI for Forest Monitoring",
  "Digital Watermarking",
  "Robot Companions",
  "Cloud-Native AI Platforms",
  "Cryptographic Agility",
  "AI in Chemical Engineering",
  "Predictive Policing Technologies",
  "Robotics in Mining",
  "Automated Food Preparation",
  "AI-Powered Writing Tools",
  "Digital Carbon Footprints",
  "Virtual Training Simulations",
  "AI in Retail Analytics",
  "Conversational AI Trends",
  "Smart Office Sensors",
  "Intelligent Energy Grids",
  "AI for Retail Demand Forecasting",
  "Climate Data Analytics",
  "Digital Supply Chains",
  "Sustainable Cloud Computing",
  "AI in Talent Acquisition",
  "Synthetic Voice Regulation",
  "Digital Trust Solutions",
  "AI for Personalized Education",
  "Privacy in Smart Vehicles",
  "Privacy in Wearables",
  "AI for Real Estate Valuation",
  "Energy Storage Innovation",
  "AI for Food Safety",
  "Privacy Enhancing Computation",
  "Smart Textiles",
  "Digital Health Passports",
  "Zero-Emission Data Centers",
  "Robotics for Remote Inspections",
  "Smart Mobility Solutions",
  "AI in Cinematography",
  "AI for Market Research",
  "Voice-Activated Payments",
  "Smart Solar Panels",
  "Decentralized Cloud Storage",
  "Satellite Data Analytics",
  "Bioelectronic Medicine",
  "Robotics in Recycling",
  "Virtual Labs for Students",
  "Sustainable Semiconductor Manufacturing",
  "AI for Load Balancing",
  "Voice User Interface Trends",
  "Smart Mirrors in Retail",
  "Digital Human Models",
  "Generative Art Algorithms",
  "Biohybrid Robots",
  "Robotics in Disaster Recovery",
  "AI for Predictive Hiring",
  "Energy Efficient AI Models",
  "AI for Retail Loss Prevention",
  "Autonomous Drones for Firefighting",
  "Digital Signature Security",
  "Privacy in Home Assistants",
  "AI for Air Traffic Control",
  "Biometric Data Regulation",
  "Digital Asset Management Systems",
  "Tech for Plastic Pollution",
  "AI for Translation Services",
  "Robotic Law Enforcement",
  "Cloud-Native Data Lakes",
  "IoT in Agriculture",
  "Emotion Detection in Gaming",
  "AI for Document Summarization",
  "Smart Farming Robots",
  "Digital Resilience Strategies",
  "AI for Emergency Medical Services",
  "Voice-Driven Coding",
  "Robot Bartenders",
  "Computer Vision for Retail Shelves",
  "Cloud FinOps",
  "AI for Urban Planning",
  "Energy Blockchain Applications",
  "AI for Geospatial Data",
  "Privacy Labels on Apps",
  "Smart Hydration Devices",
  "Digital Twins for Factories",
  "Robot Cleaners in Public Spaces",
  "Cognitive Digital Twins",
  "Microfactories",
  "Quantum Internet Security",
  "Voice Search Optimization",
  "Digital Currency Wallets",
  "Blockchain in Pharma Supply Chains",
  "Digital Procurement Tools",
  "Real-Time Emotion Tracking",
  "Robotics for Surgery",
  "Biodegradable Electronics",
  "Robotics in Food Harvesting",
  "AI for Remote Sensing",
  "Tech for Clean Oceans",
  "Digital Art Marketplaces",
  "AI in Behavioral Analytics",
  "Smart Home Energy Systems",
  "Drone Light Shows",
  "Digital Copyright Management",
  "Automated Code Generation",
  "Generative Video Creation",
  "Digital Plant Monitoring",
  "Computer Vision in Retail Checkout",
  "AI in Risk Management",
  "Digital Twin Cities",
  "Blockchain for Copyright Protection",
  "Smart Waste Sorting Systems",
  "AI in Predictive Text",
  "Augmented Reality Work Instructions",
  "Automated Warehouse Vehicles",
  "Privacy in AI Training Data",
  "Smart City Lighting",
  "AI for Food Quality Control",
  "Digital Asset Tokenization",
  "AI in Contract Review",
  "AI in Precision Agriculture",
  "Crowdsourced Data Labeling",
  "Personalized Audio Experiences",
  "AI for Intelligent Tutoring",
  "Digital Health Ecosystems",
  "Blockchain for Supply Chain Visibility",
  "AI in Inventory Management",
  "Green Tech Investments",
  "AI for Financial Fraud Detection",
  "Digital Therapeutic Apps",
  "Digital Twin Supply Chains",
  "AI-Driven Inventory Optimization",
  "Smart Building Analytics",
  "Biometric Authentication Trends",
  "Virtual Personal Shoppers",
  "AI for Waste Reduction",
  "Decentralized Identity Solutions",
  "AI in Clinical Trials",
  "Smart Glass Applications",
  "Digital Content Watermarking",
  "AI-Driven Art Restoration",
  "Autonomous Street Cleaning",
  "AI for Predicting Disease Outbreaks",
  "Computer Vision in Manufacturing",
  "Autonomous Underwater Vehicles",
  "AI in Predictive Customer Service",
  "Automated Legal Advice",
  "Smart Roads",
  "AI in Traffic Optimization",
  "Robotic Fish for Ocean Studies",
  "Digital Water Management",
  "AI for Automated Translation",
  "Blockchain for Carbon Credits",
  "Emotion Detection in Virtual Meetings",
  "Smart Bike Systems",
  "Blockchain for Clinical Trials",
  "AI-Generated Comic Art",
  "Digital Patient Records",
  "Smart Outdoor Advertising",
  "AI in Online Education",
  "Smart Pet Care",
  "Smart Textile Sensors",
  "Autonomous Public Transport",
  "AI-Generated Fashion",
  "Smart Hotel Rooms",
  "AI for Sustainable Retail",
  "Digital Art Authentication",
  "Voice Technology in Cars",
  "Smart Windows",
  "AI in Digital Publishing",
  "AI for Investment Portfolios",
  "Digital Payment Fraud Detection",
  "AI in Gaming Storytelling",
  "Digital Fitness Tracking",
  "Privacy in Smart Grids",
  "AI in Market Sentiment Analysis",
  "Smart Grid Cybersecurity",
  "AI for Predictive Customer Insights",
  "Digital Asset Protection",
  "AI in Water Quality Monitoring",
  "Digital Learning Analytics",
  "Voice Cloning Ethics",
  "Smart Event Management",
  "Digital Farming Maps",
  "AI in Personalized Medicine",
  "Digital Forensics Tools",
  "Smart Paving Technologies",
  "Digital Mental Health Tools",
  "Robotic Firefighting Equipment",
  "Voice Technology in Healthcare",
  "Digital-First Insurance",
  "Smart Baby Monitors",
  "AI in Digital Storytelling",
  "Smart Forestry Management",
  "Digital Sleep Monitoring",
  "Digital Music Production",
  "AI-Enhanced Sports Analytics",
  "Digital Twin Energy Modeling",
  "Smart Kitchen Appliances",
  "Digital Banking Assistants",
  "Robotic Lifeguards",
  "Digital Veterinary Tools",
  "Digital Dance Choreography",
  "AI for Legal Compliance",
  "Smart Acoustic Sensors",
  "Digital Twin Construction Sites",
  "AI for Digital Marketing Optimization",
  "Smart Plant Care",
  "Digital Skin Analysis",
  "AI for Air Quality Prediction",
  "Smart Hearing Aids",
  "Digital Co-Working Spaces",
  "Robotics in Bridge Inspections",
  "Digital Art Installations",
  "Smart Retail Security Systems",
  "Digital Avatars in Customer Service",
  "AI in Brand Management",
  "Smart Emergency Alarms",
  "Digital Factory Twins",
  "Digital Orthodontics",
  "AI for Behavioral Targeting",
  "Digital Legal Case Management",
  "Smart Snow Removal Systems",
  "AI in Space Robotics",
  "Digital Twins in Healthcare",
  "Smart Cargo Tracking",
  "Digital Heart Health Monitors",
  "Smart Livestock Monitoring",
  "Digital Social Impact Platforms",
  "AI for Visual Search",
  "Smart Water Leak Detection",
  "AI in Fashion Recommendations",
  "Digital Home Labs",
  "Smart Inventory Robots",
  "Digital Food Traceability",
  "AI in Personalized Skincare",
  "Smart Asset Tracking",
  "Digital Avatars for Therapy",
  "AI in Document Redaction",
  "Digital Data Clean Rooms",
  "Smart Urban Noise Monitoring",
  "Digital Engagement Platforms",
  "AI-Driven Fashion Forecasting",
  "Digital Obstacle Detection",
  "Smart Pothole Detection",
  "Digital Twin Rail Networks",
  "AI for Customer Journey Mapping",
  "Smart Digital Billboards",
  "Digital Fetal Monitoring",
  "Smart Vending Machines",
  "AI in Water Leakage Detection",
  "Digital Solar Tracking Systems",
  "Smart Elevator Systems",
  "Digital Damage Detection in Buildings",
  "Smart Product Packaging",
  "Digital Gym Experiences",
  "Smart Elder Care Robots",
  "AI-Generated Video Summaries",
  "Smart Interactive Walls",
  "Digital Soil Monitoring",
  "Smart Stadium Lighting",
  "Digital Pet Training Tools",
  "Digital Mood Tracking",
  "AI for Product Pricing Optimization",
  "Digital Construction Site Safety",
  "Smart Water Quality Sensors",
  "Digital Interactive Exhibits",
  "AI in Medical Billing",
  "Smart Automated Irrigation",
  "Digital Indoor Navigation",
  "Smart Swimming Pool Monitoring",
  "AI for Text Style Transfer",
  "Smart Outdoor Lighting",
  "Digital Urban Mobility Planning",
  "Smart Street Furniture",
  "Digital Personalized Workouts",
  "AI for Sustainable Fashion",
  "Smart Crowd Management",
  "Digital Vineyard Management",
  "AI for Personalized Sleep Coaching"
];


export const getNewTopic = async () => {
  const usedTopics = await getTopicsUsed();
  const availableTopics = techTopics.filter(
    (topic) => !usedTopics.includes(topic)
  );
  if (availableTopics.length === 0) {
    throw new Error("No available topics left to choose from");
  }
  const randomIndex = Math.floor(Math.random() * availableTopics.length);
  return availableTopics[randomIndex];
};