const techTopics = [
  "Artificial Intelligence in Healthcare",
  "Edge AI vs Cloud AI",
  "Future of Large Language Models",
  "Generative AI Use Cases",
  "Prompt Engineering Techniques",
  "Zero Trust Security",
  "Quantum Computing Basics",
  "Quantum Cryptography",
  "Ethics in AI Development",
  "Bias in Machine Learning Models",
  "Low-Code No-Code Platforms",
  "Serverless Architecture",
  "Containerization with Docker",
  "Kubernetes Best Practices",
  "Infrastructure as Code",
  "DevOps Culture",
  "Site Reliability Engineering",
  "Chaos Engineering",
  "Observability vs Monitoring",
  "FinOps in Cloud",
  "Cloud Cost Optimization",
  "Data Privacy Laws (GDPR, CCPA)",
  "Explainable AI",
  "Neural Network Architectures",
  "Federated Learning",
  "Reinforcement Learning Applications",
  "Self-Supervised Learning",
  "AI in Cybersecurity",
  "Natural Language Processing",
  "Speech Recognition Advances",
  "Computer Vision Trends",
  "Digital Twins in Industry",
  "IoT Security Challenges",
  "5G and Edge Computing",
  "Blockchain for Supply Chain",
  "NFTs beyond Art",
  "Smart Contracts Use Cases",
  "DeFi Explained",
  "Blockchain Scalability Solutions",
  "Web3 and Decentralized Apps",
  "Cybersecurity Threats 2025",
  "Phishing Prevention Techniques",
  "SOC Modernization",
  "Dark Web Intelligence",
  "Zero-Day Vulnerabilities",
  "Passwordless Authentication",
  "Digital Identity Management",
  "Privacy Enhancing Technologies",
  "Homomorphic Encryption",
  "Multi-Factor Authentication Trends",
  "Post-Quantum Cryptography",
  "Open Source Security",
  "Data Fabric Architecture",
  "Data Mesh vs Data Lakehouse",
  "Modern Data Stack",
  "Data Governance Challenges",
  "Real-Time Data Analytics",
  "Streaming Data with Kafka",
  "ETL vs ELT",
  "Data Quality Metrics",
  "Big Data Trends",
  "Graph Databases Use Cases",
  "Time-Series Databases",
  "SQL vs NoSQL Debate",
  "Headless CMS Platforms",
  "Composable Architecture",
  "API Management",
  "API Security",
  "REST vs GraphQL",
  "API Documentation Best Practices",
  "Software Design Patterns",
  "SOLID Principles in Practice",
  "Clean Code Techniques",
  "Code Review Culture",
  "Pair Programming Benefits",
  "Technical Debt Management",
  "Refactoring Legacy Systems",
  "Agile Methodologies",
  "Scrum vs Kanban",
  "Lean Software Development",
  "Product Discovery Process",
  "Design Sprints",
  "User Story Mapping",
  "MVP Development Strategy",
  "Startup Tech Challenges",
  "Scaling Engineering Teams",
  "Hiring for Tech Roles",
  "Retention in Tech Teams",
  "Mentorship in Tech",
  "Women in Technology",
  "Inclusive Product Design",
  "Accessibility in Tech",
  "Neurodiversity in Tech",
  "Career Switching into Tech",
  "Remote Work for Developers",
  "Hybrid Work Culture",
  "Product-Led Growth",
  "Customer-Centric Development",
  "UX Research Methods",
  "User Testing Best Practices",
  "Design Systems",
  "Motion Design in UX",
  "Microinteractions in UI",
  "Dark Mode UX Considerations",
  "Typography in UI Design",
  "Designing for Mobile",
  "Progressive Web Apps",
  "Cross-Platform Development",
  "Flutter vs React Native",
  "React.js Ecosystem",
  "Vue.js vs React.js",
  "Svelte in Production",
  "Micro-Frontend Architecture",
  "WebAssembly Use Cases",
  "JavaScript Framework Fatigue",
  "TypeScript Adoption",
  "Functional Programming in JS",
  "RxJS and Reactive Programming",
  "Front-End Performance Optimization",
  "Lazy Loading Techniques",
  "Static Site Generators",
  "Jamstack Architecture",
  "SEO for SPAs",
  "Browser Security Features",
  "Web Accessibility Guidelines",
  "Responsive Web Design",
  "CSS Grid vs Flexbox",
  "Tailwind CSS Best Practices",
  "State Management Libraries",
  "Monorepos vs Polyrepos",
  "CI/CD Pipelines",
  "GitOps Explained",
  "Terraform in Cloud Infrastructure",
  "Ansible vs Chef vs Puppet",
  "Cloud Native Observability",
  "Incident Response Automation",
  "Incident Retrospectives",
  "SaaS Pricing Strategies",
  "B2B vs B2C Product Differences",
  "Customer Journey Mapping",
  "User Activation Metrics",
  "A/B Testing in Product Dev",
  "Growth Hacking in Tech",
  "Venture Capital Trends",
  "Startup Fundraising Strategies",
  "Tech Due Diligence",
  "Mergers & Acquisitions in Tech",
  "IPO Readiness for Tech Cos",
  "AI Regulations Globally",
  "AI for Environmental Solutions",
  "AI in Financial Services",
  "AI for Fraud Detection",
  "Digital Health Tech",
  "Wearable Health Devices",
  "Personalized Medicine",
  "Robotic Process Automation",
  "Digital Transformation Challenges",
  "ITSM and Modern Enterprises",
  "Agile at Scale",
  "Digital Workplace Trends",
  "Virtual Collaboration Tools",
  "Digital Experience Platforms",
  "SaaS Compliance",
  "FinTech Innovations",
  "RegTech Solutions",
  "InsurTech Disruption",
  "AI in LegalTech",
  "PropTech Digitalization",
  "Cyber Insurance",
  "MarTech Trends",
  "EdTech Future",
  "Gaming Industry Tech",
  "AR in Retail",
  "VR in Healthcare",
  "Mixed Reality Use Cases",
  "Spatial Computing",
  "Metaverse Development Tools",
  "3D Modeling in Tech",
  "Digital Avatars",
  "Privacy in the Metaverse",
  "Data Sovereignty Issues",
  "Digital Sustainability",
  "Green Coding Practices",
  "Energy-Efficient Data Centers",
  "e-Waste Management",
  "Circular Economy in Tech",
  "Digital Carbon Footprint",
  "Tech for Good Initiatives",
  "Women Founders in Tech",
  "Tech and Mental Health",
  "Productivity Hacks for Engineers",
  "Burnout in Tech",
  "Engineering Leadership Lessons",
  "Product Management Myths",
  "Technical Writing Skills",
  "Public Speaking for Techies",
  "Personal Branding in Tech",
  "Building a LinkedIn Presence",
  "Networking Strategies",
  "Conference Speaking Tips",
  "Blogging as a Developer",
  "Podcasting for Tech",
  "Tech Book Recommendations",
  "Learning Roadmaps for Tech",
  "Interview Prep for Engineers",
  "System Design Interviews",
  "Behavioral Interviews",
  "Salary Negotiation in Tech",
  "Freelancing in Tech",
  "Tech Consulting",
  "Tech Entrepreneurship",
  "Remote Freelance Platforms",
  "Digital Nomad Life",
  "Open Source Contributions",
  "Hackathons Participation",
  "Patents in Tech",
  "Legal Aspects of Software Dev",
  "GDPR Compliance in Software",
  "US Data Privacy Laws",
  "China’s Tech Regulations",
  "Data Localization Laws",
  "Tech in Emerging Markets",
  "Digital Payments Evolution",
  "Buy Now Pay Later Tech",
  "Tech in Supply Chain",
  "Robotics Automation",
  "Cobots in Manufacturing",
  "Smart Warehousing",
  "Drones in Logistics",
  "Satellite Tech Innovations",
  "Autonomous Vehicles",
  "EV Charging Infrastructure",
  "Battery Tech Advancements",
  "Smart Cities Development",
  "Urban Tech Trends",
  "PropTech SaaS",
  "Digital Twins in Buildings",
  "3D Printing in Industry",
  "Additive Manufacturing",
  "Cyber Physical Systems",
  "Industrial IoT",
  "Predictive Maintenance",
  "Digital Manufacturing",
  "Cyber Warfare Trends",
  "Digital Espionage",
  "AI in Military Applications",
  "Space Tech Startups",
  "Asteroid Mining",
  "Satcom Innovations",
  "Undersea Cables Security",
  "Green Cloud Computing",
  "Multi-Cloud Strategies",
  "Cloud Interoperability",
  "Cloud Regulatory Compliance",
  "IoT Connectivity Protocols",
  "LPWAN Technologies",
  "Industrial Automation Software",
  "Tech Ethics Committees",
  "Corporate Digital Responsibility",
  "Digital Skills Gap",
  "Upskilling in Tech",
  "Tech Apprenticeships",
  "Diversity Metrics in Tech",
  "Disability Inclusion in Tech",
  "AI in Agriculture",
  "Food Tech Innovations",
  "Vertical Farming Technology",
  "Supply Chain Traceability",
  "Digital Farming Platforms",
  "Smart Grid Technology",
  "Energy Trading Platforms",
  "CleanTech Startups",
  "Environmental Data Platforms",
  "Ocean Tech Innovations",
  "Digital Twins in Energy",
  "Nuclear Tech Innovations",
  "Battery Recycling Technology",
  "Data Storytelling",
  "AI Art and Creativity",
  "Ethical AI Art",
  "Deepfake Detection",
  "Synthetic Media Future",
  "AI and Music Generation",
  "Voice Cloning Ethics",
  "AI Writing Tools",
  "AI and Copyright Laws",
  "AI and Journalism",
  "LLM Hallucinations",
  "Memory in AI Models",
  "TinyML Applications",
  "On-Device AI",
  "AI in Wearables",
  "Emotion AI",
  "Digital Assistants Evolution",
  "Conversational AI",
  "Chatbot Design Best Practices",
  "Speech Synthesis Advances",
  "Voice UX Design",
  "Emotion Detection via Voice",
  "AI in Video Analysis",
  "Sports Tech Innovations",
  "Fan Engagement Tech",
  "Smart Stadiums",
  "Esports Analytics",
  "Digital Refereeing Systems",
  "Fantasy Sports Platforms",
  "Microservices vs Monoliths",
  "Domain-Driven Design",
  "Event-Driven Architecture",
  "CQRS Pattern",
  "Hexagonal Architecture",
  "Test-Driven Development",
  "Behavior-Driven Development",
  "API Contract Testing",
  "Unit Testing Tools",
  "Integration Testing Strategies",
  "Performance Testing",
  "Load Testing with k6",
  "Security Testing Tools",
  "Penetration Testing Techniques",
  "Static Code Analysis",
  "Dependency Management",
  "Package Vulnerability Scanning",
  "Code Quality Metrics",
  "DevSecOps Practices",
  "Data Ethics",
  "Digital Twins in Healthcare",
  "AI in Biotech",
  "Personal Genomics",
  "Bioinformatics Trends",
  "Genome Sequencing Tech",
  "Health Data Privacy",
  "Medical Devices Software",
  "Regulations in Health Tech",
  "Digital Biomarkers",
  "Telemedicine Future",
  "Wearable Tech Regulations",
  "Mental Health Apps",
  "Digital Therapeutics",
  "Patient Engagement Platforms",
  "Health Chatbots",
  "AI for Medical Imaging",
  "Smart Hospitals",
  "Remote Patient Monitoring",
  "Predictive Health Analytics",
  "AI in Clinical Trials",
  "Healthcare Interoperability",
  "FHIR Standards",
  "Electronic Health Records",
  "Blockchain for Health Data",
  "Precision Medicine",
  "Cancer Detection Algorithms",
  "Radiology AI",
  "Surgical Robotics",
  "AR in Surgery",
  "VR in Medical Training",
  "Assistive Tech for Disabilities",
  "Prosthetics Innovation",
  "Exoskeletons for Mobility",
  "Smart Contact Lenses",
  "Digital Pathology",
  "AI for Drug Discovery",
  "Synthetic Biology",
  "DNA Data Storage",
  "Biohacking",
  "Lab Automation",
  "Green Biotechnology",
  "Cell and Gene Therapy",
  "Digital Farming Data Platforms",
  "Weather Tech Innovations",
  "Climate Modeling with AI",
  "Carbon Capture Tech",
  "Environmental IoT Sensors",
  "Smart Irrigation Systems",
  "Tech for Disaster Response",
  "Emergency Alert Systems",
  "Digital Risk Management",
  "Digital Twins in Transportation",
  "Fleet Management Systems",
  "Vehicle Telematics",
  "Smart Parking Solutions",
  "EV Fleet Operations",
  "Drone Delivery Systems",
  "Autonomous Drones",
  "Air Traffic Management Tech",
  "Space Debris Tracking",
  "Satellite Imagery Analysis",
  "Digital Asset Management",
  "Knowledge Graphs",
  "Data Lineage Tools",
  "Data Catalog Platforms",
  "Data Product Thinking",
  "Product Analytics",
  "Feature Flagging",
  "Release Management",
  "Tech Debt Documentation",
  "Developer Experience (DevEx)",
  "Engineering Productivity Metrics",
  "Platform Engineering",
  "Internal Developer Platforms",
  "Software Supply Chain Security",
  "Dependency Confusion Attacks",
  "Software Bill of Materials",
  "API Economy",
  "Digital Marketplaces",
  "Tech Marketplaces",
  "Micro SaaS Startups",
  "AI Co-Pilots for Developers",
  "AI in Game Development",
  "Procedural Content Generation",
  "Cloud Gaming Infrastructure",
  "Latency in Gaming",
  "Player Behavior Analytics",
  "Digital Collectibles",
  "Virtual Goods Economy",
  "Blockchain Gaming",
  "Play-to-Earn Models",
  "Digital Twin Avatars",
  "Virtual Influencers",
  "Digital Identity in Web3",
  "Tech Trends for 2030",
];


export const getNewTopic = () => {
    const randomIndex = Math.floor(Math.random() * techTopics.length);
    return techTopics[randomIndex];
}